fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  # protobuf formatting with buf
  - repo: https://github.com/bufbuild/buf
    rev: v1.65.0
    hooks:
      - id: buf-format
        args: [ "-w" ] # Overwrite files in place
        pass_filenames: true
